[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.4.3"
edition = "2024"
description = "Third state for the MacBook lid"
homepage = "https://github.com/mishamyrt/lidoff"
documentation = "https://github.com/mishamyrt/lidoff"
repository = "https://github.com/mishamyrt/lidoff"
authors = ["Mikhael Khrustik <misha@myrt.co>"]
license = "MIT"

[workspace.dependencies]
lidoff = { path = "./crates/lidoff" }
lidoff-daemon = { path = "./crates/lidoff-daemon" }
lidoff-display = { path = "./crates/lidoff-display" }
lidoff-lidsensor = { path = "./crates/lidoff-lidsensor" }
lidoff-power = { path = "./crates/lidoff-power" }

bincode = "1.3"
clap = { version = "4.5", features = ["derive"] }
serde = "1.0"
smallvec = { version = "1.15", features = ["serde"] }
thiserror = "2"
lunchd = "0.1.1"

[workspace.lints.rust]
unreachable_pub = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(codspeed)"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -2 }
char_lit_as_u8 = "allow"
collapsible_else_if = "allow"
collapsible_if = "allow"
implicit_hasher = "allow"
map_unwrap_or = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
similar_names = "allow"
single_match_else = "allow"
too_many_lines = "allow"
needless_raw_string_hashes = "allow"
print_stdout = "warn"
print_stderr = "warn"
dbg_macro = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
exit = "warn"
get_unwrap = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
rest_pat_in_fully_bound_structs = "warn"
redundant_clone = "warn"
debug_assert_with_mut_call = "warn"
unused_peekable = "warn"
large_stack_arrays = "allow"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
opt-level = "z"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
